/**
 * generated by Xtext 2.25.0
 */
package org.artemis.base.base.impl;

import org.artemis.base.base.BasePackage;
import org.artemis.base.base.SimpleTypeDecl;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Type Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleTypeDeclImpl extends TypeDeclImpl implements SimpleTypeDecl
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleTypeDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BasePackage.Literals.SIMPLE_TYPE_DECL;
  }

} //SimpleTypeDeclImpl
