/*
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.ui.tests;

import com.google.inject.Injector;
import org.artemis.spec.ui.internal.SpecActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ArtemisUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpecActivator.getInstance().getInjector("org.artemis.spec.Artemis");
	}

}
