/**
 * generated by Xtext 2.25.0
 */
package org.artemis.sm.stateMachine.impl;

import org.artemis.sm.stateMachine.ExpressionLevel8;
import org.artemis.sm.stateMachine.StateMachinePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression Level8</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpressionLevel8Impl extends ExpressionImpl implements ExpressionLevel8
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressionLevel8Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachinePackage.Literals.EXPRESSION_LEVEL8;
  }

} //ExpressionLevel8Impl
