/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis.util;

import org.artemis.spec.artemis.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.artemis.spec.artemis.ArtemisPackage
 * @generated
 */
public class ArtemisSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static ArtemisPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArtemisSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = ArtemisPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case ArtemisPackage.ARTEMIS_MODEL:
      {
        ArtemisModel artemisModel = (ArtemisModel)theEObject;
        T result = caseArtemisModel(artemisModel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.TASK:
      {
        Task task = (Task)theEObject;
        T result = caseTask(task);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.PATH:
      {
        Path path = (Path)theEObject;
        T result = casePath(path);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.TASK_PROPERTIES:
      {
        TaskProperties taskProperties = (TaskProperties)theEObject;
        T result = caseTaskProperties(taskProperties);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.PROPERTY:
      {
        Property property = (Property)theEObject;
        T result = caseProperty(property);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.PERIOD:
      {
        Period period = (Period)theEObject;
        T result = casePeriod(period);
        if (result == null) result = caseProperty(period);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.MAX_TRIES:
      {
        MaxTries maxTries = (MaxTries)theEObject;
        T result = caseMaxTries(maxTries);
        if (result == null) result = caseProperty(maxTries);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.MAX_DURATION:
      {
        MaxDuration maxDuration = (MaxDuration)theEObject;
        T result = caseMaxDuration(maxDuration);
        if (result == null) result = caseProperty(maxDuration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.MITD:
      {
        Mitd mitd = (Mitd)theEObject;
        T result = caseMitd(mitd);
        if (result == null) result = caseProperty(mitd);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.COLLECT:
      {
        Collect collect = (Collect)theEObject;
        T result = caseCollect(collect);
        if (result == null) result = caseProperty(collect);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.ON_FAIL_ACTION:
      {
        OnFailAction onFailAction = (OnFailAction)theEObject;
        T result = caseOnFailAction(onFailAction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.RESTART_PATH:
      {
        RestartPath restartPath = (RestartPath)theEObject;
        T result = caseRestartPath(restartPath);
        if (result == null) result = caseOnFailAction(restartPath);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.SKIP_PATH:
      {
        SkipPath skipPath = (SkipPath)theEObject;
        T result = caseSkipPath(skipPath);
        if (result == null) result = caseOnFailAction(skipPath);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.RESTART_TASK:
      {
        RestartTask restartTask = (RestartTask)theEObject;
        T result = caseRestartTask(restartTask);
        if (result == null) result = caseOnFailAction(restartTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case ArtemisPackage.SKIP_TASK:
      {
        SkipTask skipTask = (SkipTask)theEObject;
        T result = caseSkipTask(skipTask);
        if (result == null) result = caseOnFailAction(skipTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseArtemisModel(ArtemisModel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTask(Task object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Path</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Path</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePath(Path object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Task Properties</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Task Properties</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTaskProperties(TaskProperties object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Property</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProperty(Property object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Period</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Period</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeriod(Period object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Tries</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Tries</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxTries(MaxTries object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Duration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Duration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxDuration(MaxDuration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mitd</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mitd</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMitd(Mitd object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Collect</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Collect</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCollect(Collect object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>On Fail Action</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>On Fail Action</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOnFailAction(OnFailAction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Restart Path</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Restart Path</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRestartPath(RestartPath object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Skip Path</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Skip Path</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSkipPath(SkipPath object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Restart Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Restart Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRestartTask(RestartTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Skip Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Skip Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSkipTask(SkipTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //ArtemisSwitch
