/*
 * generated by Xtext 2.25.0
 */
package org.artemis.sm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StateMachineStandaloneSetup extends StateMachineStandaloneSetupGenerated {

	public static void doSetup() {
		new StateMachineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
