/*
 * generated by Xtext 2.25.0
 */
package org.artemis.spec;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArtemisStandaloneSetup extends ArtemisStandaloneSetupGenerated {

	public static void doSetup() {
		new ArtemisStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
