/**
 * generated by Xtext 2.25.0
 */
package org.artemis.sm.stateMachine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.sm.stateMachine.Event#getTimeVar <em>Time Var</em>}</li>
 * </ul>
 *
 * @see org.artemis.sm.stateMachine.StateMachinePackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Time Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Var</em>' containment reference.
   * @see #setTimeVar(UntypedVariable)
   * @see org.artemis.sm.stateMachine.StateMachinePackage#getEvent_TimeVar()
   * @model containment="true"
   * @generated
   */
  UntypedVariable getTimeVar();

  /**
   * Sets the value of the '{@link org.artemis.sm.stateMachine.Event#getTimeVar <em>Time Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Var</em>' containment reference.
   * @see #getTimeVar()
   * @generated
   */
  void setTimeVar(UntypedVariable value);

} // Event
