/**
 * generated by Xtext 2.25.0
 */
package org.artemis.base.tests;

import org.artemis.base.base.Model;

/* @ExtendWith(_InjectionExtension)
@InjectWith(BaseInjectorProvider.class) */@SuppressWarnings("all")
public class BaseParsingTest {
  /* @Inject
   */private /* ParseHelper<Model> */Object parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field BaseParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
