/*
 * generated by Xtext 2.25.0
 */
package org.artemis.sm.scoping;

import org.artemis.base.scoping.BaseScopeProvider;

public abstract class AbstractStateMachineScopeProvider extends BaseScopeProvider {
}
