/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.artemis.spec.artemis.ArtemisFactory
 * @model kind="package"
 * @generated
 */
public interface ArtemisPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "artemis";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.artemis.org/spec/Artemis";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "artemis";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ArtemisPackage eINSTANCE = org.artemis.spec.artemis.impl.ArtemisPackageImpl.init();

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.ArtemisModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.ArtemisModelImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getArtemisModel()
   * @generated
   */
  int ARTEMIS_MODEL = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTEMIS_MODEL__TASKS = 0;

  /**
   * The feature id for the '<em><b>Paths</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTEMIS_MODEL__PATHS = 1;

  /**
   * The feature id for the '<em><b>Task Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTEMIS_MODEL__TASK_PROPERTIES = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTEMIS_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.TaskImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.PathImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getPath()
   * @generated
   */
  int PATH = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__ID = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__TASKS = 1;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.TaskPropertiesImpl <em>Task Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.TaskPropertiesImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getTaskProperties()
   * @generated
   */
  int TASK_PROPERTIES = 3;

  /**
   * The feature id for the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_PROPERTIES__TASK = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_PROPERTIES__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Task Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_PROPERTIES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.PropertyImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 4;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__ON_FAIL_ACTION = 0;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.PeriodImpl <em>Period</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.PeriodImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getPeriod()
   * @generated
   */
  int PERIOD = 5;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIOD__ON_FAIL_ACTION = PROPERTY__ON_FAIL_ACTION;

  /**
   * The feature id for the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIOD__PERIOD = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max Attempts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIOD__MAX_ATTEMPTS = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>On Fail Max Attempt Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIOD__ON_FAIL_MAX_ATTEMPT_ACTION = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Period</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIOD_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.MaxTriesImpl <em>Max Tries</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.MaxTriesImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMaxTries()
   * @generated
   */
  int MAX_TRIES = 6;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_TRIES__ON_FAIL_ACTION = PROPERTY__ON_FAIL_ACTION;

  /**
   * The feature id for the '<em><b>Nr Tries</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_TRIES__NR_TRIES = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Max Tries</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_TRIES_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.MaxDurationImpl <em>Max Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.MaxDurationImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMaxDuration()
   * @generated
   */
  int MAX_DURATION = 7;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION__ON_FAIL_ACTION = PROPERTY__ON_FAIL_ACTION;

  /**
   * The feature id for the '<em><b>Max Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION__MAX_DURATION = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Max Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.MitdImpl <em>Mitd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.MitdImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMitd()
   * @generated
   */
  int MITD = 8;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD__ON_FAIL_ACTION = PROPERTY__ON_FAIL_ACTION;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD__DURATION = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Depends On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD__DEPENDS_ON = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Max Attempts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD__MAX_ATTEMPTS = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>On Fail Max Attempt Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD__ON_FAIL_MAX_ATTEMPT_ACTION = PROPERTY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Mitd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MITD_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.CollectImpl <em>Collect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.CollectImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getCollect()
   * @generated
   */
  int COLLECT = 9;

  /**
   * The feature id for the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECT__ON_FAIL_ACTION = PROPERTY__ON_FAIL_ACTION;

  /**
   * The feature id for the '<em><b>Nr Items</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECT__NR_ITEMS = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Depends On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECT__DEPENDS_ON = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Collect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECT_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.OnFailActionImpl <em>On Fail Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.OnFailActionImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getOnFailAction()
   * @generated
   */
  int ON_FAIL_ACTION = 10;

  /**
   * The number of structural features of the '<em>On Fail Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_FAIL_ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.RestartPathImpl <em>Restart Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.RestartPathImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getRestartPath()
   * @generated
   */
  int RESTART_PATH = 11;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART_PATH__PATH = ON_FAIL_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Restart Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART_PATH_FEATURE_COUNT = ON_FAIL_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.SkipPathImpl <em>Skip Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.SkipPathImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getSkipPath()
   * @generated
   */
  int SKIP_PATH = 12;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_PATH__PATH = ON_FAIL_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Skip Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_PATH_FEATURE_COUNT = ON_FAIL_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.RestartTaskImpl <em>Restart Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.RestartTaskImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getRestartTask()
   * @generated
   */
  int RESTART_TASK = 13;

  /**
   * The number of structural features of the '<em>Restart Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTART_TASK_FEATURE_COUNT = ON_FAIL_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.artemis.spec.artemis.impl.SkipTaskImpl <em>Skip Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.spec.artemis.impl.SkipTaskImpl
   * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getSkipTask()
   * @generated
   */
  int SKIP_TASK = 14;

  /**
   * The number of structural features of the '<em>Skip Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_TASK_FEATURE_COUNT = ON_FAIL_ACTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.ArtemisModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.artemis.spec.artemis.ArtemisModel
   * @generated
   */
  EClass getArtemisModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.spec.artemis.ArtemisModel#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see org.artemis.spec.artemis.ArtemisModel#getTasks()
   * @see #getArtemisModel()
   * @generated
   */
  EReference getArtemisModel_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.spec.artemis.ArtemisModel#getPaths <em>Paths</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paths</em>'.
   * @see org.artemis.spec.artemis.ArtemisModel#getPaths()
   * @see #getArtemisModel()
   * @generated
   */
  EReference getArtemisModel_Paths();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.spec.artemis.ArtemisModel#getTaskProperties <em>Task Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task Properties</em>'.
   * @see org.artemis.spec.artemis.ArtemisModel#getTaskProperties()
   * @see #getArtemisModel()
   * @generated
   */
  EReference getArtemisModel_TaskProperties();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.artemis.spec.artemis.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.artemis.spec.artemis.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see org.artemis.spec.artemis.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Path#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.artemis.spec.artemis.Path#getId()
   * @see #getPath()
   * @generated
   */
  EAttribute getPath_Id();

  /**
   * Returns the meta object for the reference list '{@link org.artemis.spec.artemis.Path#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Tasks</em>'.
   * @see org.artemis.spec.artemis.Path#getTasks()
   * @see #getPath()
   * @generated
   */
  EReference getPath_Tasks();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.TaskProperties <em>Task Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Properties</em>'.
   * @see org.artemis.spec.artemis.TaskProperties
   * @generated
   */
  EClass getTaskProperties();

  /**
   * Returns the meta object for the reference '{@link org.artemis.spec.artemis.TaskProperties#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Task</em>'.
   * @see org.artemis.spec.artemis.TaskProperties#getTask()
   * @see #getTaskProperties()
   * @generated
   */
  EReference getTaskProperties_Task();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.spec.artemis.TaskProperties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.artemis.spec.artemis.TaskProperties#getProperties()
   * @see #getTaskProperties()
   * @generated
   */
  EReference getTaskProperties_Properties();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.artemis.spec.artemis.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the containment reference '{@link org.artemis.spec.artemis.Property#getOnFailAction <em>On Fail Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>On Fail Action</em>'.
   * @see org.artemis.spec.artemis.Property#getOnFailAction()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_OnFailAction();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Period <em>Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Period</em>'.
   * @see org.artemis.spec.artemis.Period
   * @generated
   */
  EClass getPeriod();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Period#getPeriod <em>Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Period</em>'.
   * @see org.artemis.spec.artemis.Period#getPeriod()
   * @see #getPeriod()
   * @generated
   */
  EAttribute getPeriod_Period();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Period#getMaxAttempts <em>Max Attempts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Attempts</em>'.
   * @see org.artemis.spec.artemis.Period#getMaxAttempts()
   * @see #getPeriod()
   * @generated
   */
  EAttribute getPeriod_MaxAttempts();

  /**
   * Returns the meta object for the containment reference '{@link org.artemis.spec.artemis.Period#getOnFailMaxAttemptAction <em>On Fail Max Attempt Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>On Fail Max Attempt Action</em>'.
   * @see org.artemis.spec.artemis.Period#getOnFailMaxAttemptAction()
   * @see #getPeriod()
   * @generated
   */
  EReference getPeriod_OnFailMaxAttemptAction();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.MaxTries <em>Max Tries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Max Tries</em>'.
   * @see org.artemis.spec.artemis.MaxTries
   * @generated
   */
  EClass getMaxTries();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.MaxTries#getNrTries <em>Nr Tries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nr Tries</em>'.
   * @see org.artemis.spec.artemis.MaxTries#getNrTries()
   * @see #getMaxTries()
   * @generated
   */
  EAttribute getMaxTries_NrTries();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.MaxDuration <em>Max Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Max Duration</em>'.
   * @see org.artemis.spec.artemis.MaxDuration
   * @generated
   */
  EClass getMaxDuration();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.MaxDuration#getMaxDuration <em>Max Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Duration</em>'.
   * @see org.artemis.spec.artemis.MaxDuration#getMaxDuration()
   * @see #getMaxDuration()
   * @generated
   */
  EAttribute getMaxDuration_MaxDuration();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Mitd <em>Mitd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mitd</em>'.
   * @see org.artemis.spec.artemis.Mitd
   * @generated
   */
  EClass getMitd();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Mitd#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.artemis.spec.artemis.Mitd#getDuration()
   * @see #getMitd()
   * @generated
   */
  EAttribute getMitd_Duration();

  /**
   * Returns the meta object for the reference '{@link org.artemis.spec.artemis.Mitd#getDependsOn <em>Depends On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Depends On</em>'.
   * @see org.artemis.spec.artemis.Mitd#getDependsOn()
   * @see #getMitd()
   * @generated
   */
  EReference getMitd_DependsOn();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Mitd#getMaxAttempts <em>Max Attempts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Attempts</em>'.
   * @see org.artemis.spec.artemis.Mitd#getMaxAttempts()
   * @see #getMitd()
   * @generated
   */
  EAttribute getMitd_MaxAttempts();

  /**
   * Returns the meta object for the containment reference '{@link org.artemis.spec.artemis.Mitd#getOnFailMaxAttemptAction <em>On Fail Max Attempt Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>On Fail Max Attempt Action</em>'.
   * @see org.artemis.spec.artemis.Mitd#getOnFailMaxAttemptAction()
   * @see #getMitd()
   * @generated
   */
  EReference getMitd_OnFailMaxAttemptAction();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.Collect <em>Collect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collect</em>'.
   * @see org.artemis.spec.artemis.Collect
   * @generated
   */
  EClass getCollect();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.Collect#getNrItems <em>Nr Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nr Items</em>'.
   * @see org.artemis.spec.artemis.Collect#getNrItems()
   * @see #getCollect()
   * @generated
   */
  EAttribute getCollect_NrItems();

  /**
   * Returns the meta object for the reference '{@link org.artemis.spec.artemis.Collect#getDependsOn <em>Depends On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Depends On</em>'.
   * @see org.artemis.spec.artemis.Collect#getDependsOn()
   * @see #getCollect()
   * @generated
   */
  EReference getCollect_DependsOn();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.OnFailAction <em>On Fail Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>On Fail Action</em>'.
   * @see org.artemis.spec.artemis.OnFailAction
   * @generated
   */
  EClass getOnFailAction();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.RestartPath <em>Restart Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Restart Path</em>'.
   * @see org.artemis.spec.artemis.RestartPath
   * @generated
   */
  EClass getRestartPath();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.RestartPath#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.artemis.spec.artemis.RestartPath#getPath()
   * @see #getRestartPath()
   * @generated
   */
  EAttribute getRestartPath_Path();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.SkipPath <em>Skip Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skip Path</em>'.
   * @see org.artemis.spec.artemis.SkipPath
   * @generated
   */
  EClass getSkipPath();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.spec.artemis.SkipPath#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.artemis.spec.artemis.SkipPath#getPath()
   * @see #getSkipPath()
   * @generated
   */
  EAttribute getSkipPath_Path();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.RestartTask <em>Restart Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Restart Task</em>'.
   * @see org.artemis.spec.artemis.RestartTask
   * @generated
   */
  EClass getRestartTask();

  /**
   * Returns the meta object for class '{@link org.artemis.spec.artemis.SkipTask <em>Skip Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skip Task</em>'.
   * @see org.artemis.spec.artemis.SkipTask
   * @generated
   */
  EClass getSkipTask();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ArtemisFactory getArtemisFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.ArtemisModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.ArtemisModelImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getArtemisModel()
     * @generated
     */
    EClass ARTEMIS_MODEL = eINSTANCE.getArtemisModel();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTEMIS_MODEL__TASKS = eINSTANCE.getArtemisModel_Tasks();

    /**
     * The meta object literal for the '<em><b>Paths</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTEMIS_MODEL__PATHS = eINSTANCE.getArtemisModel_Paths();

    /**
     * The meta object literal for the '<em><b>Task Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTEMIS_MODEL__TASK_PROPERTIES = eINSTANCE.getArtemisModel_TaskProperties();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.TaskImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.PathImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH__ID = eINSTANCE.getPath_Id();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH__TASKS = eINSTANCE.getPath_Tasks();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.TaskPropertiesImpl <em>Task Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.TaskPropertiesImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getTaskProperties()
     * @generated
     */
    EClass TASK_PROPERTIES = eINSTANCE.getTaskProperties();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_PROPERTIES__TASK = eINSTANCE.getTaskProperties_Task();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_PROPERTIES__PROPERTIES = eINSTANCE.getTaskProperties_Properties();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.PropertyImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>On Fail Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__ON_FAIL_ACTION = eINSTANCE.getProperty_OnFailAction();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.PeriodImpl <em>Period</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.PeriodImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getPeriod()
     * @generated
     */
    EClass PERIOD = eINSTANCE.getPeriod();

    /**
     * The meta object literal for the '<em><b>Period</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIOD__PERIOD = eINSTANCE.getPeriod_Period();

    /**
     * The meta object literal for the '<em><b>Max Attempts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIOD__MAX_ATTEMPTS = eINSTANCE.getPeriod_MaxAttempts();

    /**
     * The meta object literal for the '<em><b>On Fail Max Attempt Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERIOD__ON_FAIL_MAX_ATTEMPT_ACTION = eINSTANCE.getPeriod_OnFailMaxAttemptAction();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.MaxTriesImpl <em>Max Tries</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.MaxTriesImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMaxTries()
     * @generated
     */
    EClass MAX_TRIES = eINSTANCE.getMaxTries();

    /**
     * The meta object literal for the '<em><b>Nr Tries</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAX_TRIES__NR_TRIES = eINSTANCE.getMaxTries_NrTries();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.MaxDurationImpl <em>Max Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.MaxDurationImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMaxDuration()
     * @generated
     */
    EClass MAX_DURATION = eINSTANCE.getMaxDuration();

    /**
     * The meta object literal for the '<em><b>Max Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAX_DURATION__MAX_DURATION = eINSTANCE.getMaxDuration_MaxDuration();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.MitdImpl <em>Mitd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.MitdImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getMitd()
     * @generated
     */
    EClass MITD = eINSTANCE.getMitd();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MITD__DURATION = eINSTANCE.getMitd_Duration();

    /**
     * The meta object literal for the '<em><b>Depends On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MITD__DEPENDS_ON = eINSTANCE.getMitd_DependsOn();

    /**
     * The meta object literal for the '<em><b>Max Attempts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MITD__MAX_ATTEMPTS = eINSTANCE.getMitd_MaxAttempts();

    /**
     * The meta object literal for the '<em><b>On Fail Max Attempt Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MITD__ON_FAIL_MAX_ATTEMPT_ACTION = eINSTANCE.getMitd_OnFailMaxAttemptAction();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.CollectImpl <em>Collect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.CollectImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getCollect()
     * @generated
     */
    EClass COLLECT = eINSTANCE.getCollect();

    /**
     * The meta object literal for the '<em><b>Nr Items</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECT__NR_ITEMS = eINSTANCE.getCollect_NrItems();

    /**
     * The meta object literal for the '<em><b>Depends On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECT__DEPENDS_ON = eINSTANCE.getCollect_DependsOn();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.OnFailActionImpl <em>On Fail Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.OnFailActionImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getOnFailAction()
     * @generated
     */
    EClass ON_FAIL_ACTION = eINSTANCE.getOnFailAction();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.RestartPathImpl <em>Restart Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.RestartPathImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getRestartPath()
     * @generated
     */
    EClass RESTART_PATH = eINSTANCE.getRestartPath();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTART_PATH__PATH = eINSTANCE.getRestartPath_Path();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.SkipPathImpl <em>Skip Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.SkipPathImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getSkipPath()
     * @generated
     */
    EClass SKIP_PATH = eINSTANCE.getSkipPath();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SKIP_PATH__PATH = eINSTANCE.getSkipPath_Path();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.RestartTaskImpl <em>Restart Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.RestartTaskImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getRestartTask()
     * @generated
     */
    EClass RESTART_TASK = eINSTANCE.getRestartTask();

    /**
     * The meta object literal for the '{@link org.artemis.spec.artemis.impl.SkipTaskImpl <em>Skip Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.spec.artemis.impl.SkipTaskImpl
     * @see org.artemis.spec.artemis.impl.ArtemisPackageImpl#getSkipTask()
     * @generated
     */
    EClass SKIP_TASK = eINSTANCE.getSkipTask();

  }

} //ArtemisPackage
