/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.spec.artemis.Collect#getNrItems <em>Nr Items</em>}</li>
 *   <li>{@link org.artemis.spec.artemis.Collect#getDependsOn <em>Depends On</em>}</li>
 * </ul>
 *
 * @see org.artemis.spec.artemis.ArtemisPackage#getCollect()
 * @model
 * @generated
 */
public interface Collect extends Property
{
  /**
   * Returns the value of the '<em><b>Nr Items</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nr Items</em>' attribute.
   * @see #setNrItems(int)
   * @see org.artemis.spec.artemis.ArtemisPackage#getCollect_NrItems()
   * @model
   * @generated
   */
  int getNrItems();

  /**
   * Sets the value of the '{@link org.artemis.spec.artemis.Collect#getNrItems <em>Nr Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nr Items</em>' attribute.
   * @see #getNrItems()
   * @generated
   */
  void setNrItems(int value);

  /**
   * Returns the value of the '<em><b>Depends On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depends On</em>' reference.
   * @see #setDependsOn(Task)
   * @see org.artemis.spec.artemis.ArtemisPackage#getCollect_DependsOn()
   * @model
   * @generated
   */
  Task getDependsOn();

  /**
   * Sets the value of the '{@link org.artemis.spec.artemis.Collect#getDependsOn <em>Depends On</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depends On</em>' reference.
   * @see #getDependsOn()
   * @generated
   */
  void setDependsOn(Task value);

} // Collect
