/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Max Duration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.spec.artemis.MaxDuration#getMaxDuration <em>Max Duration</em>}</li>
 * </ul>
 *
 * @see org.artemis.spec.artemis.ArtemisPackage#getMaxDuration()
 * @model
 * @generated
 */
public interface MaxDuration extends Property
{
  /**
   * Returns the value of the '<em><b>Max Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Duration</em>' attribute.
   * @see #setMaxDuration(double)
   * @see org.artemis.spec.artemis.ArtemisPackage#getMaxDuration_MaxDuration()
   * @model
   * @generated
   */
  double getMaxDuration();

  /**
   * Sets the value of the '{@link org.artemis.spec.artemis.MaxDuration#getMaxDuration <em>Max Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Duration</em>' attribute.
   * @see #getMaxDuration()
   * @generated
   */
  void setMaxDuration(double value);

} // MaxDuration
