/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.spec.artemis.Property#getOnFailAction <em>On Fail Action</em>}</li>
 * </ul>
 *
 * @see org.artemis.spec.artemis.ArtemisPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>On Fail Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Fail Action</em>' containment reference.
   * @see #setOnFailAction(OnFailAction)
   * @see org.artemis.spec.artemis.ArtemisPackage#getProperty_OnFailAction()
   * @model containment="true"
   * @generated
   */
  OnFailAction getOnFailAction();

  /**
   * Sets the value of the '{@link org.artemis.spec.artemis.Property#getOnFailAction <em>On Fail Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Fail Action</em>' containment reference.
   * @see #getOnFailAction()
   * @generated
   */
  void setOnFailAction(OnFailAction value);

} // Property
