/**
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.artemis;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Restart Task</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.artemis.spec.artemis.ArtemisPackage#getRestartTask()
 * @model
 * @generated
 */
public interface RestartTask extends OnFailAction
{
} // RestartTask
