/**
 * generated by Xtext 2.25.0
 */
package org.artemis.sm.stateMachine.util;

import org.artemis.sm.stateMachine.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.artemis.sm.stateMachine.StateMachinePackage
 * @generated
 */
public class StateMachineSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static StateMachinePackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StateMachineSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = StateMachinePackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case StateMachinePackage.MONITOR:
      {
        Monitor monitor = (Monitor)theEObject;
        T result = caseMonitor(monitor);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.STATE_MACHINE:
      {
        StateMachine stateMachine = (StateMachine)theEObject;
        T result = caseStateMachine(stateMachine);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.STATE:
      {
        State state = (State)theEObject;
        T result = caseState(state);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.TRANSITION:
      {
        Transition transition = (Transition)theEObject;
        T result = caseTransition(transition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EVENT:
      {
        Event event = (Event)theEObject;
        T result = caseEvent(event);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.START_TASK:
      {
        StartTask startTask = (StartTask)theEObject;
        T result = caseStartTask(startTask);
        if (result == null) result = caseEvent(startTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.END_TASK:
      {
        EndTask endTask = (EndTask)theEObject;
        T result = caseEndTask(endTask);
        if (result == null) result = caseEvent(endTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.ANY_EVENT:
      {
        AnyEvent anyEvent = (AnyEvent)theEObject;
        T result = caseAnyEvent(anyEvent);
        if (result == null) result = caseEvent(anyEvent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.VARIABLE:
      {
        Variable variable = (Variable)theEObject;
        T result = caseVariable(variable);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.UNTYPED_VARIABLE:
      {
        UntypedVariable untypedVariable = (UntypedVariable)theEObject;
        T result = caseUntypedVariable(untypedVariable);
        if (result == null) result = caseVariable(untypedVariable);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.TYPED_VARIABLE:
      {
        TypedVariable typedVariable = (TypedVariable)theEObject;
        T result = caseTypedVariable(typedVariable);
        if (result == null) result = caseVariable(typedVariable);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.ACTION:
      {
        Action action = (Action)theEObject;
        T result = caseAction(action);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.ASSIGNMENT_ACTION:
      {
        AssignmentAction assignmentAction = (AssignmentAction)theEObject;
        T result = caseAssignmentAction(assignmentAction);
        if (result == null) result = caseAction(assignmentAction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.ON_FAIL_ACTION:
      {
        OnFailAction onFailAction = (OnFailAction)theEObject;
        T result = caseOnFailAction(onFailAction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.RESTART_PATH:
      {
        RestartPath restartPath = (RestartPath)theEObject;
        T result = caseRestartPath(restartPath);
        if (result == null) result = caseOnFailAction(restartPath);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.SKIP_PATH:
      {
        SkipPath skipPath = (SkipPath)theEObject;
        T result = caseSkipPath(skipPath);
        if (result == null) result = caseOnFailAction(skipPath);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.RESTART_TASK:
      {
        RestartTask restartTask = (RestartTask)theEObject;
        T result = caseRestartTask(restartTask);
        if (result == null) result = caseOnFailAction(restartTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.SKIP_TASK:
      {
        SkipTask skipTask = (SkipTask)theEObject;
        T result = caseSkipTask(skipTask);
        if (result == null) result = caseOnFailAction(skipTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION:
      {
        Expression expression = (Expression)theEObject;
        T result = caseExpression(expression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_NOT:
      {
        ExpressionNot expressionNot = (ExpressionNot)theEObject;
        T result = caseExpressionNot(expressionNot);
        if (result == null) result = caseExpression(expressionNot);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_MINUS:
      {
        ExpressionMinus expressionMinus = (ExpressionMinus)theEObject;
        T result = caseExpressionMinus(expressionMinus);
        if (result == null) result = caseExpression(expressionMinus);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_PLUS:
      {
        ExpressionPlus expressionPlus = (ExpressionPlus)theEObject;
        T result = caseExpressionPlus(expressionPlus);
        if (result == null) result = caseExpression(expressionPlus);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_LEVEL8:
      {
        ExpressionLevel8 expressionLevel8 = (ExpressionLevel8)theEObject;
        T result = caseExpressionLevel8(expressionLevel8);
        if (result == null) result = caseExpression(expressionLevel8);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_BRACKET:
      {
        ExpressionBracket expressionBracket = (ExpressionBracket)theEObject;
        T result = caseExpressionBracket(expressionBracket);
        if (result == null) result = caseExpressionLevel8(expressionBracket);
        if (result == null) result = caseExpression(expressionBracket);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_CONSTANT_BOOL:
      {
        ExpressionConstantBool expressionConstantBool = (ExpressionConstantBool)theEObject;
        T result = caseExpressionConstantBool(expressionConstantBool);
        if (result == null) result = caseExpressionLevel8(expressionConstantBool);
        if (result == null) result = caseExpression(expressionConstantBool);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_CONSTANT_INT:
      {
        ExpressionConstantInt expressionConstantInt = (ExpressionConstantInt)theEObject;
        T result = caseExpressionConstantInt(expressionConstantInt);
        if (result == null) result = caseExpressionLevel8(expressionConstantInt);
        if (result == null) result = caseExpression(expressionConstantInt);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_CONSTANT_REAL:
      {
        ExpressionConstantReal expressionConstantReal = (ExpressionConstantReal)theEObject;
        T result = caseExpressionConstantReal(expressionConstantReal);
        if (result == null) result = caseExpressionLevel8(expressionConstantReal);
        if (result == null) result = caseExpression(expressionConstantReal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_CONSTANT_STRING:
      {
        ExpressionConstantString expressionConstantString = (ExpressionConstantString)theEObject;
        T result = caseExpressionConstantString(expressionConstantString);
        if (result == null) result = caseExpressionLevel8(expressionConstantString);
        if (result == null) result = caseExpression(expressionConstantString);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_VARIABLE:
      {
        ExpressionVariable expressionVariable = (ExpressionVariable)theEObject;
        T result = caseExpressionVariable(expressionVariable);
        if (result == null) result = caseExpressionLevel8(expressionVariable);
        if (result == null) result = caseExpression(expressionVariable);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_AND:
      {
        ExpressionAnd expressionAnd = (ExpressionAnd)theEObject;
        T result = caseExpressionAnd(expressionAnd);
        if (result == null) result = caseExpression(expressionAnd);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_OR:
      {
        ExpressionOr expressionOr = (ExpressionOr)theEObject;
        T result = caseExpressionOr(expressionOr);
        if (result == null) result = caseExpression(expressionOr);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_EQUAL:
      {
        ExpressionEqual expressionEqual = (ExpressionEqual)theEObject;
        T result = caseExpressionEqual(expressionEqual);
        if (result == null) result = caseExpression(expressionEqual);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_NEQUAL:
      {
        ExpressionNEqual expressionNEqual = (ExpressionNEqual)theEObject;
        T result = caseExpressionNEqual(expressionNEqual);
        if (result == null) result = caseExpression(expressionNEqual);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_GEQ:
      {
        ExpressionGeq expressionGeq = (ExpressionGeq)theEObject;
        T result = caseExpressionGeq(expressionGeq);
        if (result == null) result = caseExpression(expressionGeq);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_GREATER:
      {
        ExpressionGreater expressionGreater = (ExpressionGreater)theEObject;
        T result = caseExpressionGreater(expressionGreater);
        if (result == null) result = caseExpression(expressionGreater);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_LEQ:
      {
        ExpressionLeq expressionLeq = (ExpressionLeq)theEObject;
        T result = caseExpressionLeq(expressionLeq);
        if (result == null) result = caseExpression(expressionLeq);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_LESS:
      {
        ExpressionLess expressionLess = (ExpressionLess)theEObject;
        T result = caseExpressionLess(expressionLess);
        if (result == null) result = caseExpression(expressionLess);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_ADDITION:
      {
        ExpressionAddition expressionAddition = (ExpressionAddition)theEObject;
        T result = caseExpressionAddition(expressionAddition);
        if (result == null) result = caseExpression(expressionAddition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_SUBTRACTION:
      {
        ExpressionSubtraction expressionSubtraction = (ExpressionSubtraction)theEObject;
        T result = caseExpressionSubtraction(expressionSubtraction);
        if (result == null) result = caseExpression(expressionSubtraction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_MULTIPLY:
      {
        ExpressionMultiply expressionMultiply = (ExpressionMultiply)theEObject;
        T result = caseExpressionMultiply(expressionMultiply);
        if (result == null) result = caseExpression(expressionMultiply);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_DIVISION:
      {
        ExpressionDivision expressionDivision = (ExpressionDivision)theEObject;
        T result = caseExpressionDivision(expressionDivision);
        if (result == null) result = caseExpression(expressionDivision);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_MAXIMUM:
      {
        ExpressionMaximum expressionMaximum = (ExpressionMaximum)theEObject;
        T result = caseExpressionMaximum(expressionMaximum);
        if (result == null) result = caseExpression(expressionMaximum);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_MINIMUM:
      {
        ExpressionMinimum expressionMinimum = (ExpressionMinimum)theEObject;
        T result = caseExpressionMinimum(expressionMinimum);
        if (result == null) result = caseExpression(expressionMinimum);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case StateMachinePackage.EXPRESSION_POWER:
      {
        ExpressionPower expressionPower = (ExpressionPower)theEObject;
        T result = caseExpressionPower(expressionPower);
        if (result == null) result = caseExpression(expressionPower);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Monitor</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Monitor</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMonitor(Monitor object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>State Machine</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>State Machine</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStateMachine(StateMachine object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>State</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>State</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseState(State object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Transition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Transition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTransition(Transition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Event</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEvent(Event object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Start Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Start Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStartTask(StartTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>End Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>End Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEndTask(EndTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Any Event</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Any Event</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAnyEvent(AnyEvent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Variable</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseVariable(Variable object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Untyped Variable</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Untyped Variable</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUntypedVariable(UntypedVariable object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Typed Variable</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Typed Variable</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTypedVariable(TypedVariable object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Action</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAction(Action object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Assignment Action</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Assignment Action</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAssignmentAction(AssignmentAction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>On Fail Action</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>On Fail Action</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOnFailAction(OnFailAction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Restart Path</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Restart Path</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRestartPath(RestartPath object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Skip Path</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Skip Path</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSkipPath(SkipPath object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Restart Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Restart Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRestartTask(RestartTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Skip Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Skip Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSkipTask(SkipTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpression(Expression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Not</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Not</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionNot(ExpressionNot object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Minus</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Minus</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMinus(ExpressionMinus object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Plus</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Plus</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionPlus(ExpressionPlus object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Level8</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Level8</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionLevel8(ExpressionLevel8 object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Bracket</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Bracket</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionBracket(ExpressionBracket object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Constant Bool</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Constant Bool</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionConstantBool(ExpressionConstantBool object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Constant Int</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Constant Int</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionConstantInt(ExpressionConstantInt object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Constant Real</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Constant Real</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionConstantReal(ExpressionConstantReal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Constant String</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Constant String</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionConstantString(ExpressionConstantString object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Variable</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Variable</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionVariable(ExpressionVariable object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression And</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression And</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionAnd(ExpressionAnd object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Or</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Or</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionOr(ExpressionOr object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Equal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Equal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionEqual(ExpressionEqual object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression NEqual</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression NEqual</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionNEqual(ExpressionNEqual object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Geq</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Geq</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionGeq(ExpressionGeq object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Greater</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Greater</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionGreater(ExpressionGreater object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Leq</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Leq</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionLeq(ExpressionLeq object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Less</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Less</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionLess(ExpressionLess object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Addition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Addition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionAddition(ExpressionAddition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Subtraction</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Subtraction</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionSubtraction(ExpressionSubtraction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Multiply</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Multiply</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMultiply(ExpressionMultiply object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Division</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Division</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionDivision(ExpressionDivision object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Maximum</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Maximum</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMaximum(ExpressionMaximum object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Minimum</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Minimum</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMinimum(ExpressionMinimum object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Power</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Power</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionPower(ExpressionPower object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //StateMachineSwitch
