/*
 * generated by Xtext 2.25.0
 */
package org.artemis.spec.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArtemisScopeProvider extends DelegatingScopeProvider {
}
