/**
 * generated by Xtext 2.25.0
 */
package org.artemis.base.base;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.artemis.base.base.BaseFactory
 * @model kind="package"
 * @generated
 */
public interface BasePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "base";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.artemis.org/base/Base";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "base";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BasePackage eINSTANCE = org.artemis.base.base.impl.BasePackageImpl.init();

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.ModelImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TYPES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.TypeDeclImpl <em>Type Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.TypeDeclImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getTypeDecl()
   * @generated
   */
  int TYPE_DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECL__NAME = 0;

  /**
   * The number of structural features of the '<em>Type Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.SimpleTypeDeclImpl <em>Simple Type Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.SimpleTypeDeclImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getSimpleTypeDecl()
   * @generated
   */
  int SIMPLE_TYPE_DECL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TYPE_DECL__NAME = TYPE_DECL__NAME;

  /**
   * The number of structural features of the '<em>Simple Type Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TYPE_DECL_FEATURE_COUNT = TYPE_DECL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.EnumTypeDeclImpl <em>Enum Type Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.EnumTypeDeclImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getEnumTypeDecl()
   * @generated
   */
  int ENUM_TYPE_DECL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DECL__NAME = TYPE_DECL__NAME;

  /**
   * The feature id for the '<em><b>Literals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DECL__LITERALS = TYPE_DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum Type Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DECL_FEATURE_COUNT = TYPE_DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.EnumElementImpl <em>Enum Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.EnumElementImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getEnumElement()
   * @generated
   */
  int ENUM_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Enum Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.TypeImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getType()
   * @generated
   */
  int TYPE = 6;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.ArrayImpl <em>Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.ArrayImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getArray()
   * @generated
   */
  int ARRAY = 5;

  /**
   * The feature id for the '<em><b>Base Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__BASE_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.artemis.base.base.impl.TypeRefImpl <em>Type Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.artemis.base.base.impl.TypeRefImpl
   * @see org.artemis.base.base.impl.BasePackageImpl#getTypeRef()
   * @generated
   */
  int TYPE_REF = 7;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_REF__TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_REF_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.artemis.base.base.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.artemis.base.base.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.base.base.Model#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.artemis.base.base.Model#getTypes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Types();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.TypeDecl <em>Type Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Decl</em>'.
   * @see org.artemis.base.base.TypeDecl
   * @generated
   */
  EClass getTypeDecl();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.base.base.TypeDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.artemis.base.base.TypeDecl#getName()
   * @see #getTypeDecl()
   * @generated
   */
  EAttribute getTypeDecl_Name();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.SimpleTypeDecl <em>Simple Type Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Type Decl</em>'.
   * @see org.artemis.base.base.SimpleTypeDecl
   * @generated
   */
  EClass getSimpleTypeDecl();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.EnumTypeDecl <em>Enum Type Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Type Decl</em>'.
   * @see org.artemis.base.base.EnumTypeDecl
   * @generated
   */
  EClass getEnumTypeDecl();

  /**
   * Returns the meta object for the containment reference list '{@link org.artemis.base.base.EnumTypeDecl#getLiterals <em>Literals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Literals</em>'.
   * @see org.artemis.base.base.EnumTypeDecl#getLiterals()
   * @see #getEnumTypeDecl()
   * @generated
   */
  EReference getEnumTypeDecl_Literals();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.EnumElement <em>Enum Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Element</em>'.
   * @see org.artemis.base.base.EnumElement
   * @generated
   */
  EClass getEnumElement();

  /**
   * Returns the meta object for the attribute '{@link org.artemis.base.base.EnumElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.artemis.base.base.EnumElement#getName()
   * @see #getEnumElement()
   * @generated
   */
  EAttribute getEnumElement_Name();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.Array <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array</em>'.
   * @see org.artemis.base.base.Array
   * @generated
   */
  EClass getArray();

  /**
   * Returns the meta object for the reference '{@link org.artemis.base.base.Array#getBaseType <em>Base Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Base Type</em>'.
   * @see org.artemis.base.base.Array#getBaseType()
   * @see #getArray()
   * @generated
   */
  EReference getArray_BaseType();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.artemis.base.base.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.artemis.base.base.TypeRef <em>Type Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Ref</em>'.
   * @see org.artemis.base.base.TypeRef
   * @generated
   */
  EClass getTypeRef();

  /**
   * Returns the meta object for the reference '{@link org.artemis.base.base.TypeRef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.artemis.base.base.TypeRef#getType()
   * @see #getTypeRef()
   * @generated
   */
  EReference getTypeRef_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BaseFactory getBaseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.ModelImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TYPES = eINSTANCE.getModel_Types();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.TypeDeclImpl <em>Type Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.TypeDeclImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getTypeDecl()
     * @generated
     */
    EClass TYPE_DECL = eINSTANCE.getTypeDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_DECL__NAME = eINSTANCE.getTypeDecl_Name();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.SimpleTypeDeclImpl <em>Simple Type Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.SimpleTypeDeclImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getSimpleTypeDecl()
     * @generated
     */
    EClass SIMPLE_TYPE_DECL = eINSTANCE.getSimpleTypeDecl();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.EnumTypeDeclImpl <em>Enum Type Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.EnumTypeDeclImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getEnumTypeDecl()
     * @generated
     */
    EClass ENUM_TYPE_DECL = eINSTANCE.getEnumTypeDecl();

    /**
     * The meta object literal for the '<em><b>Literals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_TYPE_DECL__LITERALS = eINSTANCE.getEnumTypeDecl_Literals();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.EnumElementImpl <em>Enum Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.EnumElementImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getEnumElement()
     * @generated
     */
    EClass ENUM_ELEMENT = eINSTANCE.getEnumElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_ELEMENT__NAME = eINSTANCE.getEnumElement_Name();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.ArrayImpl <em>Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.ArrayImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getArray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getArray();

    /**
     * The meta object literal for the '<em><b>Base Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY__BASE_TYPE = eINSTANCE.getArray_BaseType();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.TypeImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.artemis.base.base.impl.TypeRefImpl <em>Type Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.artemis.base.base.impl.TypeRefImpl
     * @see org.artemis.base.base.impl.BasePackageImpl#getTypeRef()
     * @generated
     */
    EClass TYPE_REF = eINSTANCE.getTypeRef();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_REF__TYPE = eINSTANCE.getTypeRef_Type();

  }

} //BasePackage
