/**
 * generated by Xtext 2.25.0
 */
package org.artemis.base.base;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Type Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.base.base.EnumTypeDecl#getLiterals <em>Literals</em>}</li>
 * </ul>
 *
 * @see org.artemis.base.base.BasePackage#getEnumTypeDecl()
 * @model
 * @generated
 */
public interface EnumTypeDecl extends TypeDecl
{
  /**
   * Returns the value of the '<em><b>Literals</b></em>' containment reference list.
   * The list contents are of type {@link org.artemis.base.base.EnumElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literals</em>' containment reference list.
   * @see org.artemis.base.base.BasePackage#getEnumTypeDecl_Literals()
   * @model containment="true"
   * @generated
   */
  EList<EnumElement> getLiterals();

} // EnumTypeDecl
