/**
 * generated by Xtext 2.25.0
 */
package org.artemis.base.base;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.artemis.base.base.Model#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see org.artemis.base.base.BasePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link org.artemis.base.base.TypeDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see org.artemis.base.base.BasePackage#getModel_Types()
   * @model containment="true"
   * @generated
   */
  EList<TypeDecl> getTypes();

} // Model
