/*
 * generated by Xtext 2.25.0
 */
package org.artemis.base.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBaseScopeProvider extends DelegatingScopeProvider {
}
